trackerweb/tasker/urls.py
from django.conf.urls import (
    url,
    include
)
from django.views.generic import RedirectView
import django.contrib.auth.views as auth_views
from django.contrib import admin
from . import views

task_patterns = [
    url(r'^$', views.TaskListView.as_view(), name='all'),
    url(r'^new/$', views.TaskCreateView.as_view(), name='new'),
    url(r'^archive/$', views.TaskArchiveView.as_view(), name='archive'),
    url(r'^(?P<pk>\d+)/$', views.TaskDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/finish/$', views.finish_task, name='finish'),
    url(r'^(?P<pk>\d+)/delete/$', views.TaskDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/share/$', views.share_task, name='share'),
    url(r'^(?P<pk>\d+)/restore/$', views.revive_task, name='revive'),
    url(r'^(?P<pk>\d+)/edit/$', views.TaskUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/unshare/(?P<name>\w+)/$', views.unshare_task, name='unshare'),
    url(r'^search/$', views.TaskSearchView.as_view(), name='search'),
]

plan_patterns = [
    url(r'^$', views.PlanListView.as_view(), name='all'),
    url(r'^new/$', views.PlanCreateView.as_view(), name='new'),
    url(r'^(?P<pk>\d+)/delete/$', views.PlanDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/edit/$', views.PlanUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/switch/$', views.switch_able, name='switch'),
]

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='tasks'), name='homepage'),
    url(r'^login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^tasks/', include(task_patterns, namespace='tasks')),
    url(r'^plans/', include(plan_patterns, namespace='plans')),
    url(r'^admin/', admin.site.urls),
]

trackerweb/trackerweb/urls.py
from django.conf.urls import (
    url,
    include,
)

urlpatterns = [
    url(r'^', include('tasker.urls')),
]

trackerweb/tasker/models/constants.py
from typing import NamedTuple


class Status:
    DELETED = 'Deleted'
    COMPLETED = 'Complete'
    DEADLINE_MISSED = 'Deadline missed'
    IN_PROCESS = 'In process'


PRIORITIES = [(1, 'Low'), (2, 'Medium'), (3, 'High')]

PERIODS = [(1, 'Day'), (2, 'Week'), (3, 'Month'), (4, 'Year')]

trackerweb/tasker/models/custom_exeptions.py
class TaskAlreadyAdded(Exception):
    pass

trackerweb/tasker/models/plan.py
from django.db import models
from .constants import PERIODS
from . import Task
from dateutil.relativedelta import relativedelta
from django.utils import timezone


class Plan(models.Model):
    info = models.CharField(max_length=100, default=str)
    owner = models.ForeignKey(
        'Owner',
        related_name='plans',
        null=True,
        on_delete=models.CASCADE)
    enable = models.BooleanField(default=True)
    deadline = models.DateTimeField(null=True,
                                    blank=True)
    period = models.CharField(max_length=7,
                              default=str,
                              help_text='Format: period_type(type: min, h, d, w, m, y)')

    def create_task(self):
        new_task = Task(info=self.info, plan=self, owner=self.owner)
        new_task.save()
        return new_task

    def switch_able(self):
        self.enable = not self.enable
        self.save()

    def get_delta(self):
        delta = self.period.split('_')
        if int(delta[0]) <= 0:
            raise ValueError
        if delta[1] == 'min':
            return relativedelta(minutes=int(delta[0]))
        elif delta[1] == 'h':
            return relativedelta(hours=int(delta[0]))
        elif delta[1] == 'd':
            return relativedelta(days=int(delta[0]))
        elif delta[1] == 'w':
            return relativedelta(weeks=int(delta[0]))
        elif delta[1] == 'm':
            return relativedelta(months=int(delta[0]))
        elif delta[1] == 'y':
            return relativedelta(years=int(delta[0]))
        raise ValueError

    def check_deadline(self):
        if self.deadline is not None:
            if self.deadline < timezone.now() and self.enable:
                self.deadline += self.get_delta()
                self.create_task()
                self.save()

    def __str__(self):
        return str(self.id) + "| " + self.info[:10]

trackerweb/tasker/models/task.py
from .constants import Status, PRIORITIES
from django.db import models
from django.utils import timezone
from datetime import datetime


class Task(models.Model):
    info = models.CharField(max_length=200,
                            default=str)
    deadline = models.DateTimeField(null=True,
                                    blank=True)
    create_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10,
                              default=Status.IN_PROCESS)
    tags = models.CharField(max_length=100,
                            default=str)
    parent_task = models.ForeignKey('self',
                                    on_delete=models.CASCADE,
                                    related_name='subtasks',
                                    null=True)
    priority = models.PositiveSmallIntegerField(choices=PRIORITIES,
                                                default=2)
    owner = models.ForeignKey('Owner',
                              null=True,
                              on_delete=models.CASCADE,
                              related_name='tasks',
                              related_query_name='task')
    plan = models.ForeignKey('Plan',
                             null=True,
                             on_delete=models.CASCADE)
    is_plan = models.BooleanField(default=False)
    delta = models.DateField(null=True,
                             default=None)
    deleted = models.BooleanField(default=False)

    def add_subtask(self, task):
        self.subtasks.add(task)
        self.save()

    def switch_status(self, status):
        self.status = status
        self.save()

    def revive(self):
        self.status = Status.IN_PROCESS
        self.deleted = False
        for task in self.subtasks.all():
            task.revive()
        self.save()

    def finish(self):
        self.status = Status.COMPLETED
        self.deleted = True
        self.save()
        for task in self.subtasks.all():
            task.finish()

    def delete_task(self):
        self.status = Status.DELETED
        self.deleted = True
        self.save()
        for task in self.subtasks.all():
            task.delete_task()

    def check_deadline(self):
        if self.deadline:
            if self.deadline < timezone.now() and self.status == Status.IN_PROCESS:
                self.status = Status.DEADLINE_MISSED
                self.save()

    def __str__(self):
        return str(self.id) + "| " + self.info[:10]

trackerweb/tasker/models/user.py
from django.db import models
from django.core import exceptions
from .constants import Status


class Owner(models.Model):
    nickname = models.CharField(max_length=15, unique=True, default=str)
    shared_tasks = models.ManyToManyField('Task', related_name='shared')
    my_tasks = models.ManyToManyField('Task', related_name='user_tasks')

    def add_task(self, task):
        self.tasks.add(task)
        self.save()

    def delete_task(self, task_id):
        task = self.find_task(task_id)
        task.status = Status.DELETED

    def find_task(self, task_id):
        def find_subtask(subtask):
            if subtask.exists():
                for task in subtask:
                    if task.sub.filter(pk=task_id):
                        return task.sub.get(pk=task_id)
                    else:
                        find_subtask(task.sub.all())

        if self.tasks.filter(pk=task_id).exists():
            return self.tasks.get(pk=task_id)
        else:
            task = find_subtask(self.tasks.all())
            if task.exists():
                return task
            else:
                raise exceptions.ObjectDoesNotExist

    def add_plan(self, plan):
        self.plans.add(plan)

    def apply_task(self, task):
        self.shared_tasks.add(task)
        self.save()

    def detach_task(self, task):
        self.shared_tasks.remove(task)
        self.save()

    def __str__(self):
        return self.nickname

trackerweb/tasker/forms.py
from .models import (
    Task,
    Plan,
)
from django import forms
from .models.constants import PRIORITIES


class TaskCreateForm(forms.ModelForm):
    parent_task = forms.ModelChoiceField(empty_label='Do not make subtask',
                                         queryset=Task.objects.none(),
                                         required=False)
    deadline = forms.DateTimeField(required=False,
                                   input_formats=['%H:%M %d-%m-%Y'],
                                   help_text="Format: HH:MM dd-mm-YYYY")
    priority = forms.ChoiceField(choices=PRIORITIES)
    tags = forms.CharField(required=False,
                           max_length=100)

    def __init__(self, tasks, *args, **kwargs):
        super(TaskCreateForm, self).__init__(*args, **kwargs)
        if tasks:
            self.fields['parent_task'].queryset = tasks

    class Meta:
        model = Task
        fields = ['info', 'deadline', 'tags', 'priority']


class TaskShareForm(forms.Form):
    user_to = forms.CharField(required=True,
                              max_length=10)

    def __init__(self, *args, **kwargs):
        self._users = kwargs.pop('users')
        super(TaskShareForm, self).__init__(*args, **kwargs)


class PlanModelForm(forms.ModelForm):
    deadline = forms.DateTimeField(input_formats=['%H:%M %d-%m-%Y'])

    class Meta:
        model = Plan
        fields = ['info', 'deadline', 'period']

trackerweb/tasker/views.py
from .control import Tasker
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import TaskCreateForm, TaskShareForm, PlanModelForm
from .models import Task, Plan
from django.http import Http404

db = Tasker()


def signup(request):
    if request.user.is_authenticated:
        return redirect('homepage')
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('homepage')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def finish_task(request, pk):
    username = request.user.username
    task = db.find_tasks(username, pk)
    task.finish()
    return redirect('homepage')


@login_required
def revive_task(request, pk):
    username = request.user.username
    task = db.find_tasks(username, pk)
    task.revive()
    return redirect('tasks:archive')


@login_required
def unshare_task(request, pk, name):
    username = request.user.username
    task = db.find_tasks(username, pk)
    owner = db.get_users(name)
    owner.detach_task(task)
    return redirect('homepage')


class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'tasker/task_all.html'
    model = Task
    context_object_name = 'tasks'

    def get_queryset(self):
        username = self.request.user.username
        if self.request.GET.get('order'):
            return db.get_sorted_tasks(username, self.request.GET.get('order'), self.request.GET.get('asc'))
        tasks = db.find_tasks(username)
        return tasks


class TaskArchiveView(LoginRequiredMixin, ListView):
    template_name = 'tasker/task_all.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        username = self.request.user.username
        return db.find_tasks(username, deleted=True, general=False)


class TaskCreateView(LoginRequiredMixin, CreateView):
    form_class = TaskCreateForm
    template_name = 'tasker/add-form.html'
    model = Task

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        tasks = db.find_tasks(self.request.user.username)
        kwargs.update({'tasks': tasks})
        return kwargs

    def form_valid(self, form):
        username = self.request.user.username
        new_task = form.save(commit=False)
        new_task.owner = db.get_users(self.request.user.username)
        new_task.save()
        parent_task = form.cleaned_data['parent_task']
        parent_task.add_subtask(new_task) if parent_task else db.add_created(username, 'task', new_task)
        return redirect('homepage')


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'tasker/task-details.html'

    def get_object(self, queryset=None):
        task = db.find_tasks(username=self.request.user.username, task_id=self.kwargs['pk'])
        return task


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Plan
    template_name = 'tasker/confirm.html'
    success_url = reverse_lazy('tasks:all')

    def get_queryset(self):
        user = self.request.user.username
        return db.find_tasks(user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'tasker/add-form.html'
    fields = ['info', 'deadline', 'priority', 'tags']

    def get_success_url(self):
        return reverse_lazy('tasks:detail', args=(self.object.pk,))


class TaskSearchView(TaskListView):
    def get_queryset(self):
        username = self.request.user.username
        query = ' ' + self.request.GET.get('data') + ' '
        tasks = db.find_tasks(username)
        result = list()
        if query:
            for task in tasks:
                if query in (' ' + task.tags + ' '):
                    result.append(task)
        return result


@login_required
def share_task(request, pk):
    users = db.get_users().exclude(nickname=request.user.username)
    form = TaskShareForm(request.POST or None, users=users)

    if request.method == 'POST':
        if form.is_valid():
            username = db.get_users(username=request.user.username)
            user_to = db.get_users(username=form.cleaned_data['user_to'])
            if user_to.nickname == request.user.username:
                raise Http404
            task_to_share = db.find_tasks(username, pk)
            add(username, task_to_share, user_to)
            return redirect('tasks:detail', pk)
    return render(request, 'tasker/task_share.html', {'form': form})


def add(username, task_to_share, user_to):
    user_to.apply_task(task_to_share)
    if task_to_share.subtasks.all().exists():
        for subtask in task_to_share.subtasks.all():
            add(username, subtask, user_to)


class PlanListView(LoginRequiredMixin, ListView):
    template_name = 'tasker/plan_all.html'
    context_object_name = 'plans'

    def get_queryset(self):
        username = self.request.user.username
        return db.find_plans(username)


class PlanCreateView(LoginRequiredMixin, CreateView):
    model = Plan
    form_class = PlanModelForm
    template_name = 'tasker/add-form.html'

    def form_valid(self, form):
        username = self.request.user.username
        new_plan = form.save(commit=False)
        try:
            new_plan.get_delta()
        except ValueError:
            raise Http404
        new_plan.save()
        db.add_created(username, 'plan', new_plan)
        return redirect('plans:all')


class PlanDeleteView(LoginRequiredMixin, DeleteView):
    model = Plan
    template_name = 'tasker/confirm.html'
    success_url = reverse_lazy('plans:all')

    def get_queryset(self):
        user = self.request.user.username
        return db.find_plans(user)


class PlanUpdateView(LoginRequiredMixin, UpdateView):
    model = Plan
    form_class = PlanModelForm
    template_name = 'tasker/add-form.html'

    def get_success_url(self):
        return reverse_lazy('plans:all')


@login_required()
def switch_able(request, pk):
    username = request.user.username
    plan = db.find_plans(username, pk)
    plan.switch_able()
    return redirect('plans:all')

trackerweb/tasker/templates/tasker/header.html
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'tasks:all' %}"
       style="font-family: 'BioRhyme Expanded', serif;"><b>Tasker</b></a>
    {% if request.path != 'login' and  request.path != 'signup' %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link active"
                   href="{% url 'tasks:all' %}">Tasks <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link active"
                   href="{% url 'plans:all' %}">Plans <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a style="color: white;" class="nav-link text-center" href="{% url 'tasks:archive' %}">Archive</a>
            </li>
            <li class="nav-item">
                <div class="dropdown">
                    <a class="nav-link active"
                       style="cursor: pointer;" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-plus-circle"></i> Add
                    </a>
                    <div class="dropdown-menu" style="background-color: #343a40;">
                        <a href="{% url 'tasks:new' %}" class="btn" style="text-decoration: #000000; color: white;">
                            Task</a>
                        <a href="{% url 'plans:new' %}" class="btn" style="text-decoration: #000000; color: white;">
                            Plan</a>
                    </div>
                </div>
            </li>
            <li class="nav-item navbar-right" style="margin-left: 15vw; width: 30vw;">
                <form class="form-inline" action="{% url 'tasks:search' %}" method="get"
                      accept-charset="utf-8">
                    <div class="form-group" style="width:100%;">
                        <input name="data" class="form-control" type="text" style="width:100%;"
                               placeholder="Search task by tags">
                    </div>
                </form>
            </li>
        </ul>
            {% if 'tasks' in request.path %}
            <div class="dropdown nav-item">
                <a class="nav-link text-center" style="color: white; cursor: pointer;" data-toggle="dropdown">
                    Order by
                </a>
                <div class="dropdown-menu" style="padding: 0; margin: 0">
                    <div class="btn-group" style="width: 100%">
                        <p class="nav-link" style="margin: 0; width: 100%;">Priority</p>
                        <a href="{% url 'tasks:all' %}?order=priority&asc=asc"
                           style="color: black; padding-left: 0;"
                           class=" btn fas fa-chevron-up"></a>
                        <a href="{% url 'tasks:all' %}?order=priority&asc=desc"
                           style="color: black; padding-left: 0;"
                           class="btn fas fa-chevron-down"></a>
                    </div>
                    <div class="btn-group" style="width: 100%">
                        <p class="nav-link" style="margin: 0">Deadline</p>
                        <a href="{% url 'tasks:all' %}?order=deadline&asc=asc"
                           style="color: black; padding-left: 0;"
                           class=" btn fas fa-chevron-up"></a>
                        <a href="{% url 'tasks:all' %}?order=deadline&asc=desc"
                           style="color: black; padding-left: 0;"
                           class="btn fas fa-chevron-down"></a>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="dropdown nav-item">
            <button class="btn btn-info text-center" type="button" data-toggle="dropdown">
                {{ request.user.username|upper }}
            </button>
            <div class="dropdown-menu"
                 style="background-color: #005f9e; left: auto; right: -20px;  border-radius: 20px">
                <a href="{% url 'logout' %}" class="nav-link text-center" style="color: white;">Logout</a>
            </div>
        </div>
    {% endif %}
</nav>

trackerweb/tasker/templates/tasker/plan_all.html
{% extends 'tasker/base.html' %}
{% block content %}
    <div class="d-flex flex-wrap card-group">
        {% for plan in plans %}
            <div class="flex-fill p-2">
                <div class="card-face" {% if not plan.enable %}style="opacity: .4"{% endif %}>
                    <div class="front">
                        <div class="card">
                            <div class="card-header" style="background: #ff7a66">
                            </div>
                            <div class="card-body">
                                {{ plan.info }}
                            </div>
                            <div class="card-footer" style="text-align: center">Every {{ plan.period }}
                                {% if plan.period_type == 1 %} day
                                {% elif plan.period_type == 2 %} week
                                {% elif plan.period_type == 3 %} month
                                {% elif plan.period_type == 4 %} year{% endif %}
                            </div>
                            <small class="text-muted offset-1">Nearest deadline: {{ plan.deadline|date:'N j, Y, f ' }}</small>
                        </div>
                    </div>
                    <div class="back">
                        <a href="{% url 'plans:edit' plan.pk %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'plans:switch' plan.pk %}" class="btn bg-warning" style="color: white;">
                            {% if plan.enable %}Disable{% else %}Activate{% endif %}</a>
                        <a href="{% url 'plans:delete' plan.pk %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <h1 class="display-3">No Plans</h1>
        {% endfor %}
    </div>
{% endblock %}

trackerweb/tasker/templates/tasker/task-details.html
{% extends 'tasker/base.html' %}
{% load humanize %}
{% block content %}
    <div class="form-wrapper">
        <h3 class="text-center">
            Creator:
            <b>{{ task.owner }}</b>
        </h3>
        <p style=" word-wrap: break-word;">{{ task.pk }}|{{ task.info }}</p>
        <table class="table borderless">
            <tr>
                <th>Priority:</th>
                <th>{% if task.priority == 1 %} Low
                    {% elif task.priority == 2 %} Medium
                    {% else %} High
                    {% endif%}</th>
            </tr>
            {% if task.parent_task %}
                <tr>
                    <th>Parent task:</th>
                    <th><a style="color: black; display: block"
                           href="{% url 'tasks:detail' task.parent_task.pk %}">{{ task.parent_task.info }}</a>
                </tr>
            {% endif %}
            <tr>
                <th>Deadline:</th>
                <th>{{ task.deadline|date:'N j, Y, f '|default:"No deadline" }}</th>
            </tr>
            <tr>
                <th>Status:</th>
                <th>{{ task.status }}</th>
            </tr>
            {% if task.tags|length > 0 %}
                <tr>
                <th class="btn btn-primary" data-toggle="collapse"
                    data-target="#collapseTags"
                style="width: 60%;">Tags</th>
            </tr>
            <tr>
                <td>
                    <div class="collapse" id="collapseTags">
                        <div class="card card-body">
                            <a> {{ task.tags }}</a>
                        </div>
                    </div>
                </td>
            </tr>
            {% endif %}
            {% if task.subtasks.all.exists %}
                    <tr>
                        <th class="btn btn-primary" data-toggle="collapse"
                            data-target="#collapseSubtasks"
                        style="width: 100%;">Subtasks</th>
                    </tr>
                {% for sub in task.subtasks.all %}
                    <tr>
                        <td>
                            <div class="collapse" id="collapseSubtasks">
                                <a href="{% url 'tasks:detail' sub.pk %}"
                                   {% if sub.status != 'In process' %}style="opacity: .4"{% endif %}
                                   class="btn bg-light">
                                        {{ sub.info|slice:':10' }}{% if sub.info|length > 10 %}...{% endif %}</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
            {% if task.shared.all.exists %}
                <tr>
                    <th>Owners:</th>
                {% for owner in task.shared.all %}
                        <td>
                            <div class="btn-group " style="width: 100%;">
                                <button style="width: 100%;"
                                        class="btn btn-sm">{{ owner }}</button>
                                {% if task.parent_task == None %}
                                    <a href="{% url 'tasks:unshare' pk=task.pk name=task.shared.all.first %}"
                                   class="btn bg-danger btn-sm"><i class="fas fa-trash-alt white"
                                                                   style="color: #e6e7e8"></i></a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </table>
        <table class="table borderless">
            <tr>
                <th><a style="width: 100%; color: #e6e7e8;"
                       href="{% url 'tasks:edit' task.pk %}" class="btn btn-primary ">Edit</a>
                </th>
                <th><a href="{% url 'tasks:delete' task.pk %}" style="width: 100%;" class="btn btn-danger ">Delete</a></th>
            </tr>
            <tr>
                {% if task.owner.nickname == request.user.username %}
                    {% if task.parent_task == None %}
                        {% if task.status == 'In process' %}
                            <th><a href="{% url 'tasks:share' task.pk %}" class="btn btn-warning">Share</a></th>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <th>
                {% if task.status != 'Complete' %}
                   <a href="{% url 'tasks:finish' task.pk %}" class="btn btn-success">Finish</a>
                {% endif %}
                </th>
                <th>
                    {% if task.status != 'In process' %}
                        {% if task.status != 'Deadline missed' %}
                            <a href="{% url 'tasks:revive' task.pk %}" class="btn btn-success">Revive</a>
                        {% endif %}
                    {% endif %}
                </th>
            </tr>
        </table>
    </div>
{% endblock %}

trackerweb/tasker/templates/tasker/task_all.html
{% extends 'tasker/base.html' %}
{% load humanize %}
{% block content %}
    <div class="d-flex flex-wrap card-group">
        {% for task in tasks %}
            <div class="flex-fill p-2">
                <div class="card-face">
                    <div class="front ">
                        <div class="card ">
                            {% if task.priority == 1 %}
                                <div class="card-header" style="background: #b3b3b3">
                                    Low priority
                                </div>
                            {% elif task.priority == 2 %}
                                <div class="card-header" style="background: #5294ff">
                                    Medium priority
                                </div>
                            {% else %}
                                <div class="card-header" style="background: #ffd700">
                                    High priority
                                </div>
                            {% endif %}
                            <div class="card-body">
                                {{ task.pk }}|{{ task.info|slice:':40' }}{% if task.info|length > 40 %}...{% endif %}
                            </div>
                            <div class="card-footer"
                                 style="text-align: center;{% if task.owner.all %} background: #FCE883;{% endif %}">
                                {{ task.deadline|date:'N j, Y, f '|default:'No deadline' }}
                            </div>
                            <small class="text-muted offset-1">{{ task.updated_at }}</small>
                        </div>
                    </div>
                    <div class="back">
                        <a href="{% url 'tasks:detail' task.pk %}" class="btn btn-primary">Details</a>
                        {% if task.owner.nickname == request.user.username %}
                            {% if task.status == 'In process' %}
                                <a href="{% url 'tasks:share' task.pk %}" class="btn btn-warning" style="color: white;">Share</a>
                            {% endif %}
                        {% endif %}
                        {% if not task.deleted %}
                            <a href="{% url 'tasks:finish' task.pk %}" class="btn btn-success">Finish</a>
                        {% else %}
                            <a href="{% url 'tasks:revive' task.pk %}" class="btn btn-success">Revive</a>
                        {% endif %}
                        {% if task.status == 'In process' %}
                            <a href="{% url 'tasks:delete' task.pk %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                        {% if task.status == 'Deadline missed' %}
                            <a href="{% url 'tasks:delete' task.pk %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% empty %}
            {% if 'search' in request.path %}
                <h1 class="display-3">No such tasks were found</h1>
            {% else %}
                <h1 class="display-3">No tasks</h1>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}